### ISSUE TITLE
Expecting reactions...

### ISSUE THREAD

**Issue by iherman** [w3c/json-ld-wg-charter#1]
Just pinging @azaroth42 @gkellogg @BigBlueHat @pchampin...

**Comment by gkellogg** [comment]
Looks good to me.

**Comment by davidlehn** [comment]
Why "jsonld-wg-charter" instead of "json-ld-wg-charter"?

**Comment by BigBlueHat** [comment]
Agreed with @davidlehn. All our other repos are `json-ld-`, so this one probably should be too. Thanks!

**Comment by iherman** [comment]
I have changed the repo name.

(This reminds me of an FAQ in Semantic Web circles: why is the "Web Ontology Language" called "OWL", and not "WOL". One of the standard answers is: "isn't it good to introduce some inconsistency to a language that is all about consistency?" :-)

**Comment by iherman** [comment]
Thanks to all. I am closing this issue... and wait for others.
