### ISSUE TITLE
Require tests for new features

### ISSUE THREAD

**Issue by swickr** [w3c/json-ld-wg-charter#10]
> 3. Success Criteria
...
Each substantive change should contain a section detailing all known security and privacy implications for implementers, Web authors, and end users. 
.
To promote interoperability, all changes made to specifications should have tests. 

I suggest we set the expectation by the time a spec reaches this maintenance stage that any substantive change _must_ come with tests.   Other changes can be left as _should_.

**Comment by iherman** [comment]
I am fine with that. @azaroth42 @gkellogg @BigBlueHat ?

**Comment by gkellogg** [comment]
We have always driven the spec by tests, so of course we’ll continue to do that.

**Comment by iherman** [comment]
See PR #12
