### ISSUE TITLE
Input for the new charter

### ISSUE THREAD

**Issue by sebastiankb** [w3c/json-ld-wg-charter#8]
I support the new charter initiative. The [W3C WoT Thing Description](https://www.w3.org/TR/wot-thing-description/) is one of the early adopters of the new JSON-LD 1.1. 

The WoT Group is mentioned in [4.1](https://w3c.github.io/json-ld-wg-charter/#coordination). There I would update the text 

>    Coordination on various concerns regarding the usage of JSON-LD in the WoT Architecture.

with

> Coordination of various topics concerning the use of JSON-LD by the WoT Thing Description.

**Comment by iherman** [comment]
Thank you @sebastiankb, I have made an update in https://github.com/w3c/json-ld-wg-charter/commit/e53997b6a3548450525f1cbc77ced0efa08da66e
