### ISSUE TITLE
What becomes of 1.0?

### ISSUE THREAD

**Issue by swickr** [w3c/json-ld-wg-charter#9]
The JSON-LD 1.1 specs take great pains to support compatibility with 1.0 tooling.  Unless the WG (current or future) intends to propose that the 1.1 spec supersede the 1.0 spec this charter may wish to allow maintenance (errata) of 1.0.

**Comment by iherman** [comment]
The current 1.1 document says (see the [abstract section](https://www.w3.org/TR/json-ld/):

> This specification describes a superset of the features defined in JSON-LD 1.0 [JSON-LD10] and, except where noted, documents created using the 1.0 version of this specification remain compatible with JSON-LD 1.1.

The WG has no intention to work on the 1.0 spec separately.

Once the 1.1 Spec is published as a Rec, we can officially declare 1.0 as superseded.

@azaroth42 @gkellogg @BigBlueHat

**Comment by iherman** [comment]
In agreement with @plehegar a notice on superseding has been added to the document to be published as PR tomorrow.
